name: import_sorter
description: Automatically organize your dart imports
version: 4.6.0
repository: "https://github.com/fluttercommunity/import_sorter"
homepage: "https://mattglei.ch"
maintainer: Matthew Gleich (@gleich)
authors:
  - Matthew Gleich <email@mattglei.ch>
  - Flutter Community <community@flutter.zone>

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  args: ^2.4.2
  tint: ^2.0.1
  yaml: ^3.1.2

dev_dependencies:
  test: ^1.16.7
  lints: ^3.0.0


import_sorter:
  emojis: true
