name: format

on:
  - push
  - pull_request

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          sdk: stable
      - name: Run pub get
        run: dart pub get
        working-directory: ./example/example_app
      - name: Run format
        run: dart format --set-exit-if-changed .

  import_sorter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Run import_sorter
        run: |
          dart pub get
          dart run import_sorter --exit-if-changed
